/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-15 13:51:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ES\">\n");
      out.write("\t<head>\n");
      out.write("\t\t<title> Iniciar sesión </title>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"src/style.css\"/>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t");
      out.print(vista.Util.getAttribute("error", request) );
      out.write("\n");
      out.write("\t\t\t<a id=\"volver\" href=\"main\"> Volver </a>\n");
      out.write("\t\t\t<div class=\"cajaCentrada\" style=\"height: 244px;\">\n");
      out.write("\t\t\t\t<div class=\"cajaSuperior\">\n");
      out.write("\t\t\t\t\t<h1> Iniciar sesión </h1>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<form action=\"entrar\" method=\"post\"> \n");
      out.write("\t\t\t\t\t<label>Usuario</label>\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"user\" maxlength='15'>\n");
      out.write("\t\t\t\t\t<br/><br/>\n");
      out.write("\t\t\t\t\t<label>Contraseña</label>\n");
      out.write("\t\t\t\t\t<input type=\"password\" name=\"password\" maxlength='20'>\n");
      out.write("\t\t\t\t\t<br/><br/>\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Entrar\">\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
