/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.53
 * Generated at: 2014-06-15 21:41:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"src/webstyle.css\">\n");
      out.write("\t\t<meta charset=\"UTF-8\">\n");
      out.write("\t\t\n");
      out.write("\t\t<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'></script>\n");
      out.write("\t\t<script type='text/javascript' src='src/menu_jquery.js'></script>\t\n");
      out.write("\t\t\n");
      out.write("\t</head>\n");
      out.write("\t<body>\t\n");
      out.write("\t<div id='contenedorHorizontalTop'>\n");
      out.write("\t\t<div id=\"contenedorTop\">\n");
      out.write("\t\t\t<div id=\"top\">\n");
      out.write("\t\t\t\t<div id=\"topLogo\">\n");
      out.write("\t\t\t\t\t<a href=\"main\">INFROMATIC</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"contenedorNav\">\n");
      out.write("\t\t\t<div id=\"carritoUsuario\">\n");
      out.write("\t\t\t\t");
      out.print(vista.Util.getAttribute("carritoUsuario", request));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"login\">\n");
      out.write("\t\t\t\t");
      out.print(vista.Util.getLoginBox(request));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"search\">\n");
      out.write("\t\t\t\t<img src='src/images/buscar.png'> </img><input type=\"text\" name=\"buscar\" id=\"buscador\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"menu\">\n");
      out.write("\t\t\t\t<div id='cssmenu'>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t   <li class='has-sub'><a href='#'><span>Productos</span></a>\n");
      out.write("\t\t\t\t\t      <ul>\n");
      out.write("\t\t\t\t\t      \t");
      out.print(vista.Util.getAttribute("tipos", request));
      out.write("\n");
      out.write("\t\t\t\t\t      </ul>\n");
      out.write("\t\t\t\t\t   </li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id='contenedorHorizontalProd'>\n");
      out.write("\t\t<div id=\"contenedorProd\">\n");
      out.write("\t\t\t<div id=\"contenido\">\n");
      out.write("\t\t\t\t");
      out.print(vista.Util.getAttribute("productos", request));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div id='contenedorHorizontalBottom'>\n");
      out.write("\t\t<div id=\"contenedorBottom\">\n");
      out.write("\t\t\t<div id=\"bottom\">\n");
      out.write("\t\t\t\t<div id='bottomLeft'> <img src='src/images/villadeaguimes.png'></img>\n");
      out.write("\t\t\t\t<p> Desarrollo de aplicaciones multiplataforma.</br>Proyecto tercer trimestre.</p></div>\n");
      out.write("\t\t\t\t<div id='bottomRight'> <p style=\"margin-top: 50px; width:350px;\">© 2014 David, Joseph y Eduardo.</p> </div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
